
variables:
  NUGET_PATH: 'C:\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe'
  REVIEWS_API_DEPLOY_FOLDER: 'D:\Source\Builds\Reviews.API'
  REVIEWS_ADMIN_API_DEPLOY_FOLDER: 'D:\Source\Builds\Reviews.Admin.API'

stages:
  - deploy
  
deploy_reviews_api_job:
  stage: deploy
  script:
    - '$deployFolder = $($env:REVIEWS_API_DEPLOY_FOLDER)'
    - 'Remove-Item -Path "$deployFolder" -Force -Recurse'
    - 'mkdir "$deployFolder"'
    # xcopy takes care of recursively creating required folders
    - 'xcopy /y ".\Reviews\Reviews.API\bin\" "$deployFolder"'
  dependencies:
    - build_reviews_api_job
    - test_job
  environment: development

deploy_reviews_admin_api_job:
  stage: deploy
  script:
    - '$deployFolder = $($env:REVIEWS_ADMIN_API_DEPLOY_FOLDER)'
    - 'Remove-Item -Path "$deployFolder" -Force -Recurse'
    - 'mkdir "$deployFolder"'
    # xcopy takes care of recursively creating required folders
    - 'xcopy /y ".\Reviews\Reviews.Admin.API\bin\" "$deployFolder"'
  dependencies:
    - build_reviews_admin_api_job
    - test_job
  environment: development
