image: dotnet-framework

default:
  tags:
    - dotnet-framework

include:
  - local: ci/build-test-gitlab-ci.yml
  - local: ci/test-gitlab-ci.yml
  - local: ci/deploy-test-gitlab-ci.yml

stages:
  - build
  - test
  - deploy

